# Capstone project 

In [17]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import numpy as np
import pickle


In [18]:
file = open("/Users/nitin/Desktop/AdventrueOfSherlockHolmes.txt", "r", encoding = "utf8")

# store file in list
lines = []
for i in file:
    lines.append(i)

# Convert list to string
data = ""
for i in lines:
  data = ' '. join(lines) 

#replace unnecessary stuff with space
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space

#remove unnecessary spaces 
data = data.split()
data = ' '.join(data)
data[:1000]


'The Project Gutenberg eBook of The Adventures of Sherlock Holmes, by Arthur Conan Doyle This eBook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at www.gutenberg.org. If you are not located in the United States, you will have to check the laws of the country where you are located before using this eBook. Title: The Adventures of Sherlock Holmes Author: Arthur Conan Doyle Release Date: November 29, 2002 [eBook #1661] [Most recently updated: May 20, 2019] Language: English Character set encoding: UTF-8 Produced by: an anonymous Project Gutenberg volunteer and Jose Menendez *** START OF THE PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES *** cover The Adventures of Sherlock Holmes by Arthur Conan Doyle Contents I. A Scandal in Bohemia II. The Red-Headed Lea

In [19]:
len(data)

573327

In [20]:
#Tokenization: Tokenization refers to splitting bigger text data, essays, or corpus’s into smaller segments. 
#These smaller segments can be in the form of smaller documents or lines of text data.
#They can also be a dictionary of words.


In [21]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

# saving the tokenizer for predict function
pickle.dump(tokenizer, open('token.pkl', 'wb'))

sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]


[1, 141, 130, 857, 5, 1, 1060, 5, 127, 33, 46, 590, 2585, 2586, 27]

In [22]:
len(sequence_data)

108907

In [23]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)


8606


In [24]:
sequences = []

for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)
    
print("The Length of sequences are: ", len(sequences))
sequences = np.array(sequences)
sequences[:10]


The Length of sequences are:  108904


array([[   1,  141,  130,  857],
       [ 141,  130,  857,    5],
       [ 130,  857,    5,    1],
       [ 857,    5,    1, 1060],
       [   5,    1, 1060,    5],
       [   1, 1060,    5,  127],
       [1060,    5,  127,   33],
       [   5,  127,   33,   46],
       [ 127,   33,   46,  590],
       [  33,   46,  590, 2585]])

In [25]:
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])
    
X = np.array(X)
y = np.array(y)


In [26]:
print("Data: ", X[:10])
print("Response: ", y[:10])


Data:  [[   1  141  130]
 [ 141  130  857]
 [ 130  857    5]
 [ 857    5    1]
 [   5    1 1060]
 [   1 1060    5]
 [1060    5  127]
 [   5  127   33]
 [ 127   33   46]
 [  33   46  590]]
Response:  [ 857    5    1 1060    5  127   33   46  590 2585]


In [27]:
y = to_categorical(y, num_classes=vocab_size)
y[:5]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)